<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<BaseOutputPath>$(SolutionDir)\bin\</BaseOutputPath>
	<OutputPath>$(SolutionDir)\bin\</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	<UseCommonOutputDirectory>true</UseCommonOutputDirectory>
	  
  </PropertyGroup>


	<Target Name="CopyAllReferencedAssemblies" AfterTargets="Build">
	    <ItemGroup>
		    <ResolvedFiles Include="@(ReferenceCopyLocalPaths)" />
	    </ItemGroup>
	    <Copy SourceFiles="@(ResolvedFiles)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
    </Target>


	<ItemGroup>
	  <Compile Remove="Components\TimePicker.xaml.cs" />
	</ItemGroup>
	
	                            
  <ItemGroup>
    <None Remove="Images\3643767_key_keys_main_password_privilege_icon.png" />
    <None Remove="Images\6777283_human_id_identification_identity_myaccount_icon.png" />
  </ItemGroup>
	
	                            
  <ItemGroup>
    <Page Remove="Components\TimePicker.xaml" />
    <Page Remove="Components\TimePickerStyle.xaml" />
  </ItemGroup>

  <!--<ItemGroup>
    <None Remove="3643767_key_keys_main_password_privilege_icon.png" />
    <None Remove="6777283_human_id_identification_identity_myaccount_icon.png" />
  </ItemGroup>-->

  <ItemGroup>
    <ProjectReference Include="..\BL\BL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\3643767_key_keys_main_password_privilege_icon.png" />
    <Resource Include="Images\6777283_human_id_identification_identity_myaccount_icon.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Volunteer\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="5.2.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
  </ItemGroup>

  <!--<ItemGroup>
    <Resource Include="3643767_key_keys_main_password_privilege_icon.png" />
    <Resource Include="6777283_human_id_identification_identity_myaccount_icon.png" />
  </ItemGroup>-->

</Project>
